# Generated by Django 4.1.9 on 2023-05-10 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0004_room_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='price',
            new_name='price_per_night',
        ),
    ]
