# Generated by Django 4.1.4 on 2023-05-17 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0007_bookedroom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hoteloptions',
            name='hotel',
        ),
    ]
