# Generated by Django 4.1.4 on 2023-05-17 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0008_remove_hoteloptions_hotel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='options',
            field=models.ManyToManyField(blank=True, related_name='hotel_options', to='hotel.hoteloptions'),
        ),
    ]
