# Generated by Django 4.1.4 on 2023-05-07 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0002_remove_airport_title_airport_indent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airport',
            name='latitude_deg',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='airport',
            name='longitude_deg',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=10, null=True),
        ),
    ]
