# Generated by Django 4.1.4 on 2023-05-07 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0004_alter_airport_latitude_deg_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airport',
            name='latitude_deg',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='airport',
            name='longitude_deg',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=14, null=True),
        ),
    ]
