# Generated by Django 4.1.9 on 2023-05-07 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0007_rename_airplane_title_airplane_airplane_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='airplane',
            name='airplane_number',
        ),
        migrations.AddField(
            model_name='airplane',
            name='airplane_brand',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
