# Generated by Django 4.1.9 on 2023-05-07 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0008_remove_airplane_airplane_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='airplane',
            old_name='airplane_brand',
            new_name='airplane_model',
        ),
    ]
