# Generated by Django 4.1.4 on 2023-05-10 12:43

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0010_flight_flight_airplane_alter_flight_flight_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookedFlight',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('flight', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='flight.flight')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
