# Generated by Django 4.1.4 on 2023-05-10 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0012_bookedflight_booked_date_bookedflight_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookedflight',
            name='payment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookedflight',
            name='payment_ref_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
