# Generated by Django 4.1.4 on 2023-05-13 20:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0014_bookedflight_ticket_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airplane',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='airport',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bookedflight',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='flight',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='flightprovider',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
