# Generated by Django 4.1.4 on 2023-05-07 16:32

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airplane',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('airplane_title', models.CharField(blank=True, max_length=200, null=True)),
                ('airplane_number', models.PositiveIntegerField(blank=True, null=True)),
                ('airplane_body_class', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FlightProvider',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('flight_type', models.CharField(choices=[('economy', 'economy'), ('business', 'business')], default='economy', max_length=10)),
                ('flight_destination_type', models.CharField(choices=[('internal', 'internal'), ('external', 'external')], default='internal', max_length=15)),
                ('flight_price', models.PositiveBigIntegerField(blank=True, null=True)),
                ('flight_ticket_count', models.PositiveIntegerField(blank=True, null=True)),
                ('flight_landing_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('flight_takeoff_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('flight_waiting_on_destination_airport_time', models.TimeField(blank=True, null=True)),
                ('flight_duration', models.TimeField(blank=True, null=True)),
                ('flight_maximum_load_weight', models.PositiveIntegerField(blank=True, null=True)),
                ('flight_roles', models.TextField(blank=True, null=True)),
                ('flight_number', models.PositiveIntegerField(blank=True, null=True)),
                ('flight_airport_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='airport_from', to='flight.airport')),
                ('flight_airport_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='airport_to', to='flight.airport')),
                ('flight_provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='flight.flightprovider')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
