# Generated by Django 4.1.4 on 2023-05-07 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='airport',
            name='title',
        ),
        migrations.AddField(
            model_name='airport',
            name='indent',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='airport',
            name='latitude_deg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='airport',
            name='longitude_deg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='airport',
            name='name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='airport',
            name='type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
