# Generated by Django 4.1.4 on 2023-05-07 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0005_alter_airport_latitude_deg_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airport',
            name='latitude_deg',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='airport',
            name='longitude_deg',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
