# Generated by Django 4.1.9 on 2023-05-07 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0006_alter_airport_latitude_deg_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='airplane',
            old_name='airplane_title',
            new_name='airplane_name',
        ),
    ]
