# Generated by Django 4.1.4 on 2023-05-08 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0009_rename_airplane_brand_airplane_airplane_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='flight_airplane',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flight_airplane', to='flight.airplane'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='flight_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
