# Generated by Django 4.1.9 on 2023-05-10 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('flight', '0011_bookedflight'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookedflight',
            name='booked_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookedflight',
            name='customer',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='users.user'),
            preserve_default=False,
        ),
    ]
