# Generated by Django 4.1.4 on 2023-05-10 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0013_bookedflight_payment_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookedflight',
            name='ticket_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
